language: bash
services: 
  - docker
before_install:
  - docker build -t myimg .
  - docker run -d --name mycont myimg
  - docker ps -a
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag myimg:latest myimg:latest;
    docker push myimg:latest;
    fi

